### PR TITLE
SwiftUI support

### PR DESCRIPTION
**Pull request by PangMo5**
# Changes
- Add SwiftUI support
- Add SwiftUI example
- update README.md

#5

### CODE REVIEW

**Comment by 623637646** [comment]
Thank you so much! @PangMo5 , This Pull request is so helpful! 
The MR is LGTM. Just a little concern.
How does it work in reuseable Views? Let's say, `ImpressionKit` has `ImpressionGroup` to support `UITableView` and `UICollectionView`.  Does SwiftUI need this kind of thing?

**Comment by PangMo5** [comment]
As used in the example app, no special things are needed for reusable views

**Comment by 623637646** [comment]
I see. Thanks!

**Comment by PangMo5** [comment]
Thanks to your idea XD

**Pull request merged**
